### ISSUE TITLE
Changing to current active user logs you out.

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Hipster#11]
Disable change to current user.

**Comment by iLexiconn** [comment]
That's exactly what I fixed 13 minutes ago. :p
https://github.com/iLexiconn/Hipster/commit/e88871fd10c996cf36458c90c52bcb808ac48aa9

**Comment by MrWolvetech** [comment]
Als je naar het huidige account veranderd logt hij je uit.

**Comment by JWolvers** [comment]
Sorry did not notice that.
