### ISSUE TITLE
Login buttons in side menu header

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Hipster#13]

**Comment by JWolvers** [comment]
Just add a spinner inside the header

**Comment by iLexiconn** [comment]
I have no idea how I would do that.

**Comment by MrWolvetech** [comment]
Just read the logcat message send out by the android system?

**Comment by iLexiconn** [comment]
Wrong issue :P

**Comment by MrWolvetech** [comment]
Oops :P

**Comment by JWolvers** [comment]
Add it in `main_header.xml` inside the res folder. Than just use findviewbyid just after initializing the drawer layout and set its adapter.

**Comment by iLexiconn** [comment]
I tried it, but without success. Can you take a look at it, please?

**Comment by JWolvers** [comment]
Sure I can

**Comment by iLexiconn** [comment]
Any luck so far?

**Comment by JWolvers** [comment]
I had no time tw look at it yet, I committed that 'fix' from my phone l.
