### ISSUE TITLE
Unable to login after logging off

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Hipster#2]

**Comment by JWolvers** [comment]
What's the problem?

**Comment by iLexiconn** [comment]
It keeps gixing the error `invalid password` until you restart the app.

**Comment by JWolvers** [comment]
Issue with `Magister.java` not `Hipster`

**Comment by iLexiconn** [comment]
How is this an issue with the API?

**Comment by JWolvers** [comment]
Tested it running login on pc twice the server also returns:
`Ongeldig account of verkeerde combinatie van gebruikersnaam en wachtwoord.`
