### ISSUE TITLE
Views empty after reopening app

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Hipster#5]

**Comment by JWolvers** [comment]
Move everything to `onresume` instead of  `oncreate`

**Comment by iLexiconn** [comment]
:+1:

**Comment by iLexiconn** [comment]
That didn't fix it, sadly. I've got a crash log, though. https://media.ilexiconn.net/0m9zQN7.txt

**Comment by iLexiconn** [comment]
Hmm, it only happens when you close the app using the back button.

**Comment by JWolvers** [comment]
I think the saved instance isn't getting restored. Try rotating when it isnt empty. And than report back plz.

**Comment by iLexiconn** [comment]
Yeah I disabled that, because it was also resetting the view. :p

**Comment by KeizerDev** [comment]
You have to initialise it just once.

**Comment by JWolvers** [comment]
Resetting or empty?

**Comment by iLexiconn** [comment]
Empty, and its currently only initiated once.

**Comment by JWolvers** [comment]
found the issue; It is in `Fragments.getFragment` you are returning an instance of an fragment, those instances are deleted when you exit the app, so the next time you start the app, it returns null.

**Comment by iLexiconn** [comment]
Pretty sure you're talking about the wrong method. It never returns null for me.

**Comment by JWolvers** [comment]
Well i fixed it by changing that method

**Comment by iLexiconn** [comment]
Mhm, pr? ^.^

**Comment by JWolvers** [comment]
made a pr :+1:

**Comment by iLexiconn** [comment]
Are you sure you tested it right? Now it's not only empty when I reload the app, but also when I go to a previously openen tab.

**Comment by JWolvers** [comment]
Well it doesnt go to the right tab for me either, but it is not empty anymore.

**Comment by iLexiconn** [comment]
Try going to the settings and going back to the dashboard.

**Comment by JWolvers** [comment]
I give up. cant find the issue.

**Comment by iLexiconn** [comment]
:(

**Comment by KeizerDev** [comment]
I'll look at it tomorrow if you want

**Comment by iLexiconn** [comment]
Sure, thanks :)

**Comment by JWolvers** [comment]
I finally fixed it!
could you add me as a Collaborator that would make my life a lot easier.

**Comment by iLexiconn** [comment]
:+1:
