### ISSUE TITLE
Settings view still after resume

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Hipster#8]

**Comment by JWolvers** [comment]
Sorry, I forgot to apply fix to the settingsfragment.

**Comment by iLexiconn** [comment]
Already tried to do it myself, but it didn't fix it.

**Comment by JWolvers** [comment]
Did it give an error or did it just not help?

**Comment by iLexiconn** [comment]
Did just not help.

**Comment by JWolvers** [comment]
You applied the fix to the wrong file try `SettingsFragment`

**Comment by iLexiconn** [comment]
Ah, okay. Thanks. :)
